# Generated by Django 5.2.2 on 2025-06-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_doctorpayment_payment_confirmation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorpayment',
            name='payment_confirmation',
            field=models.CharField(blank=True, choices=[('declined', 'Declined'), ('received', 'Recived')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doctorpaymentlog',
            name='payment_confirmation',
            field=models.CharField(blank=True, choices=[('declined', 'Declined'), ('received', 'Received')], max_length=20, null=True),
        ),
    ]
