# Generated by Django 5.2.2 on 2025-06-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_doctorpayment_payment_confirmation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorpaymentlog',
            name='payment_confirmation',
            field=models.CharField(blank=True, choices=[('received', 'Received'), ('declined', 'Declined')], max_length=20, null=True),
        ),
    ]
