# Generated by Django 5.2.2 on 2025-07-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_alter_doctorpayment_payment_confirmation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorpaymentlog',
            name='payment_confirmation',
            field=models.CharField(blank=True, choices=[('declined', 'Declined'), ('received', 'Received')], max_length=20, null=True),
        ),
    ]
