# Generated by Django 5.2.2 on 2025-07-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_alter_doctorpaymentlog_payment_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorpayment',
            name='payment_confirmation',
            field=models.CharField(blank=True, choices=[('received', 'Recived'), ('declined', 'Declined')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doctorpaymentlog',
            name='payment_confirmation',
            field=models.CharField(blank=True, choices=[('declined', 'Declined'), ('received', 'Received')], max_length=20, null=True),
        ),
    ]
