# Generated by Django 5.2.2 on 2025-08-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_alter_doctorpayment_payment_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorpayment',
            name='payment_confirmation',
            field=models.CharField(blank=True, choices=[('received', 'Recived'), ('declined', 'Declined')], max_length=20, null=True),
        ),
    ]
