# Generated by Django 5.2.2 on 2025-08-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0027_alter_doctorpaymentlog_payment_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorpayment',
            name='payment_confirmation',
            field=models.CharField(blank=True, choices=[('declined', 'Declined'), ('received', 'Recived')], max_length=20, null=True),
        ),
    ]
