# Generated by Django 5.2.2 on 2025-08-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0036_alter_doctorpayment_payment_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorpaymentlog',
            name='payment_confirmation',
            field=models.CharField(blank=True, choices=[('received', 'Received'), ('declined', 'Declined')], max_length=20, null=True),
        ),
    ]
