# Generated by Django 5.2.2 on 2025-08-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0037_alter_doctorpaymentlog_payment_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorpaymentlog',
            name='payment_confirmation',
            field=models.CharField(blank=True, choices=[('declined', 'Declined'), ('received', 'Received')], max_length=20, null=True),
        ),
    ]
