# Generated by Django 5.2.2 on 2025-08-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0040_alter_doctorpaymentlog_payment_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorpayment',
            name='payment_confirmation',
            field=models.CharField(blank=True, choices=[('received', 'Recived'), ('declined', 'Declined')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doctorpaymentlog',
            name='payment_confirmation',
            field=models.CharField(blank=True, choices=[('received', 'Received'), ('declined', 'Declined')], max_length=20, null=True),
        ),
    ]
