# Generated by Django 5.2.2 on 2025-08-13 13:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_boardroom_boardroominvite_boardroomparticipant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardroom',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='boardroom',
            name='end_time',
        ),
        migrations.AddField(
            model_name='boardroom',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hosted_board_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boardroom',
            name='host_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='boardroom',
            name='room_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='boardroom',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='boardroom',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
