# Generated by Django 5.2.2 on 2025-08-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_boardroom_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardroom',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
