# Generated by Django 5.2.2 on 2025-08-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_boardroom_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardroominvite',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
