# Generated by Django 5.2.2 on 2025-08-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_boardroominvite_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardroominvite',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
