# Generated by Django 5.2.2 on 2025-06-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='register_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
