# Generated by Django 5.2.2 on 2025-06-07 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomCheckSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('probable_disease', models.CharField(blank=True, max_length=255, null=True)),
                ('probable_symptoms', models.TextField(blank=True, null=True)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('weight_in_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('height_in_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('medical_history', models.TextField(blank=True, help_text='Previous conditions (e.g., diabetes, asthma)', null=True)),
                ('allergies', models.TextField(blank=True, help_text='Any known drug or food allergies', null=True)),
                ('current_medications', models.TextField(blank=True, help_text='Current medications with dosage', null=True)),
                ('vital_signs', models.TextField(blank=True, help_text='Enter vital signs (e.g., Temp: 101°F, BP: 120/80, HR: 90 bpm)', null=True)),
                ('location', models.CharField(blank=True, help_text="Enter patient's location (City, Country)", max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SymptomAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='symptom_checker.symptomchecksession')),
            ],
        ),
    ]
