# Generated by Django 5.2.2 on 2025-06-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(blank=True, choices=[('capsule', 'Capsule'), ('tablet', 'Tablet'), ('syrup', 'Syrup'), ('injection', 'Injection')], max_length=50, null=True),
        ),
    ]
