# Generated by Django 5.2.2 on 2025-06-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0002_alter_medicine_medicine_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='body_height_unit',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='body_weight_unit',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='photo',
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, help_text='Any known drug or food allergies', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_profile_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_history',
            field=models.TextField(blank=True, help_text='Previous conditions (e.g., diabetes, asthma)', null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(blank=True, choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='body_height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Please enter height in cm', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='body_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Please enter weight in kg', max_digits=7, null=True),
        ),
    ]
