# Generated by Django 5.2.2 on 2025-06-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0004_patient_email_alter_medicine_medicine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprescription',
            name='raw_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(blank=True, choices=[('capsule', 'Capsule'), ('syrup', 'Syrup'), ('tablet', 'Tablet'), ('injection', 'Injection')], max_length=50, null=True),
        ),
    ]
