# Generated by Django 5.2.2 on 2025-06-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0005_aiprescription_raw_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='current_medications',
            field=models.TextField(blank=True, help_text='Current medications with dosage', null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(blank=True, choices=[('tablet', 'Tablet'), ('injection', 'Injection'), ('capsule', 'Capsule'), ('syrup', 'Syrup')], max_length=50, null=True),
        ),
    ]
