# Generated by Django 5.2.2 on 2025-06-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0006_patient_current_medications_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorbooking',
            old_name='video_call_reuest_approve',
            new_name='video_call_request_approve',
        ),
        migrations.RenameField(
            model_name='doctorbooking',
            old_name='video_call_reuest_message',
            new_name='video_call_request_message',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(blank=True, choices=[('capsule', 'Capsule'), ('syrup', 'Syrup'), ('tablet', 'Tablet'), ('injection', 'Injection')], max_length=50, null=True),
        ),
    ]
