# Generated by Django 5.2.2 on 2025-06-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0007_rename_video_call_reuest_approve_doctorbooking_video_call_request_approve_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestedlabtest',
            name='custom_lab_test_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='suggestedmedicine',
            name='custom_medicine_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(blank=True, choices=[('syrup', 'Syrup'), ('tablet', 'Tablet'), ('injection', 'Injection'), ('capsule', 'Capsule')], max_length=50, null=True),
        ),
    ]
