# Generated by Django 5.2.2 on 2025-06-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0008_suggestedlabtest_custom_lab_test_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(blank=True, choices=[('injection', 'Injection'), ('tablet', 'Tablet'), ('syrup', 'Syrup'), ('capsule', 'Capsule')], max_length=50, null=True),
        ),
    ]
