# Generated by Django 5.2.2 on 2025-06-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0009_alter_medicine_medicine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprescription',
            name='summary_of_findings',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(blank=True, choices=[('capsule', 'Capsule'), ('injection', 'Injection'), ('syrup', 'Syrup'), ('tablet', 'Tablet')], max_length=50, null=True),
        ),
    ]
