# Generated by Django 5.2.2 on 2025-06-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0010_aiprescription_summary_of_findings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(blank=True, choices=[('capsule', 'Capsule'), ('injection', 'Injection'), ('tablet', 'Tablet'), ('syrup', 'Syrup')], max_length=50, null=True),
        ),
    ]
