# Generated by Django 5.2.2 on 2025-06-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0014_alter_medicine_medicine_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(blank=True, choices=[('syrup', 'Syrup'), ('capsule', 'Capsule'), ('tablet', 'Tablet'), ('injection', 'Injection')], max_length=50, null=True),
        ),
    ]
