# Generated by Django 5.2.2 on 2025-07-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0017_alter_medicine_medicine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='video_consultation_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(blank=True, choices=[('injection', 'Injection'), ('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup')], max_length=50, null=True),
        ),
    ]
