# Generated by Django 5.2.2 on 2025-07-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0018_doctor_video_consultation_fees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(blank=True, choices=[('capsule', 'Capsule'), ('tablet', 'Tablet'), ('injection', 'Injection'), ('syrup', 'Syrup')], max_length=50, null=True),
        ),
    ]
