# Generated by Django 5.2.2 on 2025-07-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0019_alter_medicine_medicine_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(blank=True, choices=[('capsule', 'Capsule'), ('injection', 'Injection'), ('syrup', 'Syrup'), ('tablet', 'Tablet')], max_length=50, null=True),
        ),
    ]
