# Generated by Django 5.2.2 on 2025-07-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0021_alter_medicine_medicine_type_labresultfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(blank=True, choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection')], max_length=50, null=True),
        ),
    ]
