# Generated by Django 5.2.2 on 2025-07-06 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('prescription', '0023_aiprescription_diet_chart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprescription',
            name='appointment_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_prescriptions', to='appointments.appointment'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(blank=True, choices=[('tablet', 'Tablet'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('capsule', 'Capsule')], max_length=50, null=True),
        ),
    ]
