# Generated by Django 5.2.2 on 2025-07-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0024_doctorprescription_appointment_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='hospital_end_time',
            field=models.TimeField(blank=True, help_text="Doctor's hospital duty end time", null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital_start_time',
            field=models.TimeField(blank=True, help_text="Doctor's hospital duto start time", null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='end_time',
            field=models.TimeField(blank=True, help_text="Doctor's chamber end time", null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='start_time',
            field=models.TimeField(blank=True, help_text="Doctor's chamber start time", null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(blank=True, choices=[('capsule', 'Capsule'), ('syrup', 'Syrup'), ('tablet', 'Tablet'), ('injection', 'Injection')], max_length=50, null=True),
        ),
    ]
