# Generated by Django 5.2.2 on 2025-07-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0025_doctor_hospital_end_time_doctor_hospital_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='chamber_location',
            field=models.TextField(blank=True, help_text='Enter your chamber address if any', null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(blank=True, choices=[('tablet', 'Tablet'), ('syrup', 'Syrup'), ('capsule', 'Capsule'), ('injection', 'Injection')], max_length=50, null=True),
        ),
    ]
