# Generated by Django 5.2.2 on 2025-07-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0026_doctor_chamber_location_alter_medicine_medicine_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(blank=True, choices=[('injection', 'Injection'), ('tablet', 'Tablet'), ('syrup', 'Syrup'), ('capsule', 'Capsule')], max_length=50, null=True),
        ),
    ]
