# Generated by Django 5.2.2 on 2025-07-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0028_alter_medicine_medicine_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(blank=True, choices=[('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('tablet', 'Tablet')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
    ]
