# Generated by Django 5.2.2 on 2025-07-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0029_alter_medicine_medicine_type_alter_patient_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(blank=True, choices=[('capsule', 'Capsule'), ('syrup', 'Syrup'), ('tablet', 'Tablet'), ('injection', 'Injection')], max_length=50, null=True),
        ),
    ]
