# Generated by Django 5.2.2 on 2025-07-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0032_alter_medicine_medicine_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(blank=True, choices=[('injection', 'Injection'), ('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup')], max_length=50, null=True),
        ),
    ]
