# Generated by Django 5.2.2 on 2025-08-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0034_alter_medicine_medicine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
