# Generated by Django 5.2.2 on 2025-08-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0035_doctor_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(blank=True, choices=[('tablet', 'Tablet'), ('syrup', 'Syrup'), ('capsule', 'Capsule'), ('injection', 'Injection')], max_length=50, null=True),
        ),
    ]
