# Generated by Django 5.2.2 on 2025-08-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0036_doctor_last_seen_alter_medicine_medicine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(blank=True, choices=[('syrup', 'Syrup'), ('tablet', 'Tablet'), ('injection', 'Injection'), ('capsule', 'Capsule')], max_length=50, null=True),
        ),
    ]
