# Generated by Django 5.2.2 on 2025-08-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0037_patient_is_online_patient_last_seen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(blank=True, choices=[('injection', 'Injection'), ('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup')], max_length=50, null=True),
        ),
    ]
