# Generated by Django 5.2.2 on 2025-08-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0039_alter_medicine_medicine_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(blank=True, choices=[('injection', 'Injection'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('tablet', 'Tablet')], max_length=50, null=True),
        ),
    ]
