# Generated by Django 5.2.2 on 2025-08-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0050_alter_medicine_medicine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorbooking',
            name='webrtc_room',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(blank=True, choices=[('capsule', 'Capsule'), ('injection', 'Injection'), ('tablet', 'Tablet'), ('syrup', 'Syrup')], max_length=50, null=True),
        ),
    ]
