# Generated by Django 5.2.2 on 2025-08-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0051_doctorbooking_webrtc_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorfolloupbooking',
            name='webrtc_room',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='zoommeeting',
            name='webrtc_room',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(blank=True, choices=[('capsule', 'Capsule'), ('tablet', 'Tablet'), ('injection', 'Injection'), ('syrup', 'Syrup')], max_length=50, null=True),
        ),
    ]
