# Generated by Django 5.2.2 on 2025-08-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0052_doctorfolloupbooking_webrtc_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='payout_preference',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='Monthly', max_length=16),
        ),
        migrations.AddField(
            model_name='doctor',
            name='policy_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='policy_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(blank=True, choices=[('syrup', 'Syrup'), ('tablet', 'Tablet'), ('injection', 'Injection'), ('capsule', 'Capsule')], max_length=50, null=True),
        ),
    ]
