# Generated by Django 5.2.2 on 2025-08-22 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0053_doctor_payout_preference_doctor_policy_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(blank=True, choices=[('tablet', 'Tablet'), ('injection', 'Injection'), ('capsule', 'Capsule'), ('syrup', 'Syrup')], max_length=50, null=True),
        ),
    ]
