# Generated by Django 5.2.2 on 2025-08-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0054_alter_medicine_medicine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='chamber_consultation_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='chamber_followup_consultation_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='chamber_followup_validity_days',
            field=models.PositiveIntegerField(blank=True, default=10, help_text='Follow-up discount validity in days', null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='has_chamber',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(blank=True, choices=[('capsule', 'Capsule'), ('syrup', 'Syrup'), ('tablet', 'Tablet'), ('injection', 'Injection')], max_length=50, null=True),
        ),
    ]
