# Generated by Django 5.2.2 on 2025-08-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0055_doctor_chamber_consultation_fees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_feature_doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(blank=True, choices=[('syrup', 'Syrup'), ('capsule', 'Capsule'), ('injection', 'Injection'), ('tablet', 'Tablet')], max_length=50, null=True),
        ),
    ]
