# Generated by Django 5.2.2 on 2025-08-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0058_alter_doctor_user_alter_medicine_medicine_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(blank=True, choices=[('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('tablet', 'Tablet')], max_length=50, null=True),
        ),
    ]
