# Generated by Django 5.2.2 on 2025-07-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('attendance', 'Attendance'), ('payment-due', 'Payment_due'), ('notice', 'Notice'), ('general', 'General')], max_length=100, null=True),
        ),
    ]
