# Generated by Django 5.2.2 on 2025-07-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_appointment_type_appointment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient_type',
            field=models.CharField(blank=True, choices=[('IPD', 'IPD'), ('OPD', 'OPD')], max_length=20, null=True),
        ),
    ]
