# Generated by Django 5.2.2 on 2025-06-30 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0002_paymentinvoice_payment'),
        ('prescription', '0013_alter_medicine_medicine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinvoice',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prescription.doctor'),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prescription.aiprescription'),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='invoice_type',
            field=models.CharField(choices=[('symptom-check', 'Symptom Check'), ('ai_prescription', 'AI Prescription'), ('consultation', 'Doctor Consultation'), ('direct-consultation', 'Direct Doctor Consultation'), ('video-consultation', 'Video Consultation'), ('followup-consultation', 'Follow-up Consultation'), ('followup-video-consultation', 'Follow-up Video Consultation'), ('labtest', 'Lab Test'), ('medicine', 'Medicine'), ('Others', 'Others')], max_length=30),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prescription.patient'),
        ),
    ]
