# Generated by Django 5.2.2 on 2025-06-30 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0003_paymentinvoice_doctor_paymentinvoice_prescription_and_more'),
        ('prescription', '0014_alter_medicine_medicine_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentinvoice',
            old_name='prescription',
            new_name='ai_prescription',
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='doctor_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prescription.doctorbooking'),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='doctor_followup_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prescription.doctorfolloupbooking'),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='doctor_prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prescription.doctorprescription'),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='zoom_meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prescription.zoommeeting'),
        ),
    ]
