# Generated by Django 5.2.2 on 2025-06-30 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0004_rename_prescription_paymentinvoice_ai_prescription_and_more'),
        ('prescription', '0015_alter_medicine_medicine_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='ai_prescription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_prescription_invoice', to='prescription.aiprescription'),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='doctor_booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_booking_invoice', to='prescription.doctorbooking'),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='doctor_followup_booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_followup_invoice', to='prescription.doctorfolloupbooking'),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='doctor_prescription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_prescription_invoice', to='prescription.doctorprescription'),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='zoom_meeting',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zoom_meeting_invoice', to='prescription.zoommeeting'),
        ),
    ]
