# Generated by Django 5.2.2 on 2025-07-01 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0005_alter_paymentinvoice_ai_prescription_and_more'),
        ('prescription', '0016_alter_medicine_medicine_type'),
        ('symptom_checker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinvoice',
            name='symptom_checker',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='symptom_checker_invoice', to='symptom_checker.symptomchecksession'),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='doctor_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_booking_invoice', to='prescription.doctorbooking'),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='doctor_prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_prescription_invoice', to='prescription.doctorprescription'),
        ),
    ]
