# Generated by Django 5.2.2 on 2025-07-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0006_paymentinvoice_symptom_checker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsystem',
            name='enable_payment_gateway',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='paymentsystem',
            name='method',
            field=models.CharField(choices=[('bKash', 'bKash'), ('Rocket', 'Rocket'), ('CreditCard', 'CreditCard'), ('PayPal', 'PayPal'), ('sslcommerz', 'SSLCOMERZ'), ('aamarPay', 'Aamar Pay'), ('surujPay', 'Suruj Pay'), ('others', 'Others')], max_length=50),
        ),
    ]
