# Generated by Django 5.2.2 on 2025-07-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0007_paymentsystem_enable_payment_gateway_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentsystem',
            name='enable_payment_gateway',
        ),
        migrations.AddField(
            model_name='tenantpaymentconfig',
            name='enable_payment_gateway',
            field=models.BooleanField(default=True),
        ),
    ]
