# Generated by Django 5.2.2 on 2025-07-06 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('payment_gateway', '0008_remove_paymentsystem_enable_payment_gateway_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinvoice',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_invoice', to='appointments.appointment'),
        ),
    ]
