# Generated by Django 5.2.2 on 2025-07-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0009_paymentinvoice_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='invoice_type',
            field=models.CharField(choices=[('symptom-check', 'Symptom Check'), ('ai_prescription', 'AI Prescription'), ('consultation', 'Doctor Consultation'), ('direct-consultation', 'Direct Doctor Consultation'), ('video-consultation', 'Video Consultation'), ('followup-consultation', 'Follow-up Consultation'), ('followup-video-consultation', 'Follow-up Video Consultation'), ('labtest', 'Lab Test'), ('medicine', 'Medicine'), ('appointment', 'Chamber Visit appointment'), ('Others', 'Others')], max_length=30),
        ),
    ]
