# Generated by Django 5.2.2 on 2025-08-12 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('payment_gateway', '0010_alter_paymentinvoice_invoice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinvoice',
            name='ecommerce_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecommerce_invoice', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='invoice_type',
            field=models.CharField(choices=[('symptom-check', 'Symptom Check'), ('ai_prescription', 'AI Prescription'), ('consultation', 'Doctor Consultation'), ('direct-consultation', 'Direct Doctor Consultation'), ('video-consultation', 'Video Consultation'), ('followup-consultation', 'Follow-up Consultation'), ('followup-video-consultation', 'Follow-up Video Consultation'), ('labtest', 'Lab Test'), ('medicine', 'Medicine'), ('appointment', 'Chamber Visit appointment'), ('Others', 'Others'), ('ecommerce', 'ecommerce')], max_length=30),
        ),
    ]
