# Generated by Django 5.2.2 on 2025-08-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
